# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/codecov.json
coverage:
  range: 60..100
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 60%
        threshold: 1%
    project:
      default:
        target: 60%
        threshold: 1%
ignore:
  - ".*/nocheck/.*"
  - ".*/autogen/.*"
  - ".*/generated/.*"
