# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  setup-tmate:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    runs-on: ubuntu-latest
    outputs:
      ssh-command: ${{ steps.tmate.outputs.ssh-command }}
      ssh-address: ${{ steps.tmate.outputs.ssh-address }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup tmate session
        id: tmate
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
        timeout-minutes: 10
        with:
          detached: true

  use-ssh-command:
    needs: setup-tmate
    runs-on: ubuntu-latest
    steps:
      - name: Display SSH command
        run: |
          # Send a Slack message to someone telling them they can ssh to ${{ needs.setup-tmate.outputs.ssh-address }}
