name: 🐞 Bug report
description: File a bug report
title: "[Bug]: "
labels: ["type| bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        > [!Warning]
        >
        > **Submitting real bugs.**
        >
        > submitting bugs that need to be fixed, or we may **close it**. maintainers need to set the priorities for handling tasks. Keeping the number of issues in a manageable manner is one of the ways to keep the project healthy in the long run.
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? Do you already upgraded to the latest version?
      placeholder: Version
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to that can reproduce the problem ran into to help us investigate the issue. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required.
      placeholder: Reproduction
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Tell us what you see! Expected behavior, Actual behavior, Steps To Reproduce, Screenshots, Reason Analytics(If you can) and other things you think may be helpful.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: By submitting this issue, you agree to follow our [Code of Conduct](blob/main/.github/docs/CODE_OF_CONDUCT.md).
          required: true
        - label: Read the [Documentation](blob/main/README.md) & [Contributing Guidelines](blob/main/.github/docs/CONTRIBUTING.md).
          required: true
        - label: I have searched the Issues and found no similar ones.
          required: true
        - label: I have searched [StackOverflow](https://stackoverflow.com) and not resolved my issue.
          required: true
