# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-issue-forms.json
name: 🚀 Feature request
description: File a feature request
title: "feat: "
labels: ["type|enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!
  - type: textarea
    id: describe-problem
    attributes:
      label: Describe the problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: In module [xy] we could provide following implementation..., related to issue "#4", "#5"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution
      description: Please describe the solution you'd like. A clear and concise description of what you want to happen. If you intend to submit a PR for this issue, tell us in the description. Thanks!
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: By submitting this issue, you agree to follow our [Code of Conduct](blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
        - label: Read the [Documentation](blob/main/README.md) & [Contributing Guidelines](blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: I have searched the Issues and found no similar ones.
          required: true
