catalog:
  '@actions/artifact': ^6.2.1
  '@actions/attest': ^3.2.0
  '@actions/cache': ^6.0.1
  '@actions/core': ^3.0.1
  '@actions/exec': ^3.0.0
  '@actions/expressions': ^0.3.25
  '@actions/github': ^9.1.1
  '@actions/glob': ^0.7.0
  '@actions/http-client': ^4.0.1
  '@actions/io': ^3.0.2
  '@actions/languageservice': ^0.3.20
  '@actions/tool-cache': ^4.0.0
  '@actions/workflow-parser': ^0.3.20
  octokit: ^5.0.5
  '@octokit/action': ^8.0.4
  '@octokit/openapi-types': ^27.0.0
  '@octokit/types': ^16.0.0
  '@octokit/webhooks-definitions': ^3.67.3
  debug: ^4.4.3
  '@types/debug': ^4.1.13

  # tools
  es-toolkit: ^1.47.1
  radashi: ^12.7.2
  minimatch: ^10.1.1

  # node
  execa: ^9.6.1
  ofetch: ^1.5.1
  '@antfu/ni': ^30.0.0

  # infra
  rimraf: ^6.1.3
  taze: ^19.9.2

  # core
  '@types/node': ^26.1.2
  typescript: ^7.0.2
  '@typescript/native-preview': 7.0.0-dev.20260707.2
  vitest: ^4.1.10
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.7
  vite-plus: ^0.2.7

# Prefer catalog
catalogMode: prefer
shellEmulator: true
ignoreWorkspaceRootCheck: false
allowBuilds:
  cypress: true
  esbuild: true
