catalog:
  vitepress: ^2.0.0-alpha.19
  taze: ^19.17.2
  "@types/node": ^26.6.2
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@^0.3.3
  vite-plus: ^0.3.3
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
