#file: noinspection UndefinedParamsPresent
##################################################################
# issues-helper: https://github.com/actions-cool/issues-helper
# https://github.com/marketplace/actions/issues-helper
##################################################################
name: Issue Month Statistics

on:
  schedule:
    - cron: "0 1 1 * *"

jobs:
  month-statistics:
    runs-on: ubuntu-latest
    steps:
      - name: month-statistics
        # https://github.com/marketplace/actions/issues-helper
        uses: actions-cool/issues-helper@v3
        with:
          actions: "month-statistics"
          token: ${{ secrets.GITHUB_TOKEN }}
          count-lables: "true"
