#file: noinspection UndefinedParamsPresent,UndefinedAction
name: Create Github Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release-changelog:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: ✈ Checkout sources
        uses: actions/checkout@v5
      - name: 🌿 Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: ".github/config/changelog.json"
          commitMode: true
          ignorePreReleases: ${{ !contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🚀 Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
