@file:Suppress("UnstableApiUsage")

import com.autonomousapps.DependencyAnalysisExtension

// Applied by CLASS (not via `plugins { id(...) }`) so the dependency-analysis plugin is always
// loaded from build-logic's own classloader and never resolved into the main build's classloader.
// This avoids the "Cannot set ... inMemoryCache ... loaded with ...build-logic" classloader error.
apply<com.autonomousapps.DependencyAnalysisPlugin>()

if (path == ":") {
  // NOTE: We cannot use the `dependencyAnalysis { }` typed accessor here because that accessor is
  // only generated by the Kotlin DSL when the plugin is applied via the `plugins { id(...) }`
  // block.
  // Since we apply by class (to keep DAGP on a single classloader), we reference the extension by
  // type instead.
  configure<DependencyAnalysisExtension> {
    // https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1234
    // https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1485
    structure {
      bundle("spring-boot-starter-webmvc") {
        primary("org.springframework.boot:spring-boot-starter-webmvc")
        includeDependency("org.springframework.boot:spring-boot")
        includeDependency("org.springframework.boot:spring-boot-autoconfigure")
        includeDependency("org.springframework:spring-web")
        includeDependency("org.springframework:spring-context")
        includeDependency("org.springframework:spring-aop")
        includeDependency("org.springframework:spring-beans")
        includeDependency("org.springframework:spring-expression")
        includeDependency("org.springframework:spring-core")
      }
      bundle("spring-boot-starter-webmvc-test") {
        primary("org.springframework.boot:spring-boot-starter-webmvc-test")
        includeDependency("org.springframework.boot:spring-boot-webmvc-test")
        includeDependency("org.springframework.boot:spring-boot-resttestclient")
        includeDependency("org.springframework.boot:spring-boot-test")
        includeDependency("org.springframework:spring-test")
        includeDependency("org.junit.jupiter:junit-jupiter-api")
        includeDependency("org.assertj:assertj-core")
      }
    }
  }
}
